CREATE TABLE CATEGORY
(	ID 	            SERIAL PRIMARY KEY     NOT NULL,
	CATEGORY_TYPE  TEXT NOT NULL
	);

INSERT INTO CATEGORY
( CATEGORY_TYPE ) VALUES ('Gym')

INSERT INTO CATEGORY
( CATEGORY_TYPE ) VALUES ('Grocery Store')

INSERT INTO CATEGORY
( CATEGORY_TYPE ) VALUES ('Hospital')

INSERT INTO CATEGORY
( CATEGORY_TYPE ) VALUES ('School')

UPDATE CATEGORY
SET CATEGORY_TYPE = 'Grocery Store' WHERE id = 2;
